name: Java CI with Maven

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run JaCoCo and Check Coverage
        run: mvn test jacoco:report
      - name: Verify Coverage
        run: mvn verify -Pcoverage

      - name: Upload Jacoco Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco # Maven 프로젝트의 JaCoCo 리포트 경로
